### ISSUE TITLE
Hello from 'malware'

### ISSUE THREAD

**Issue by Hezaveh** [endgameinc/RTA#5]
I tried to run RTA in my virtual windows 10 machine. Now, when I run my PowerShell or cmd as administrator I receive "[+] Hello from 'malware'" message and then terminal closes automatically.  

Any options to troubleshoot?
<img width="674" alt="hello from malware" src="https://user-images.githubusercontent.com/9043022/38748334-c178fb26-3f1b-11e8-9eb7-c7ae7108f72c.png">

**Comment by rossdwolf** [comment]
It looks like the IsolatedCommand registry key is still set from
https://git.endgames.local/RnD/eql-rules/blob/f03666580e941720a141e11da409f6bf43716a04/rta/red_ttp/uac_sdclt.py#L30

For some reason, the RTA must have exited early. If you pull up regedit.exe and navigate to
`HKCU\Software\Classes\exefile\shell\runas\command`, delete the IsolatedCommand value and it should be restored.

**Comment by shidevil** [comment]
@devonakerr I am actually facing this issue like @Hezaveh 

Running gpedit.msc will open the command prompt. I tried to find in the registry to remove the run/runonce. however it is no longer available. any idea? thanks

**Comment by shidevil** [comment]
@devonakerr @Hezaveh found the problem.

Please delete all entry in HKEY_CURRENT_USER\software\classes\MSCFile
