### ISSUE TITLE
Stuck at interactive mode Python 2.7.12

### ISSUE THREAD

**Issue by WangKaiWenCalvin** [endgameinc/RTA#9]
I am currently using Ubuntu 16.04 and I tried running RTA using Python 2.7.12 but I am stuck at the interactive mode of Python. Do you have any idea how to solve this problem? Thank you for your time. 

![image](https://user-images.githubusercontent.com/43362182/48474669-fa985c80-e835-11e8-82bc-95c009aaf9d6.png)

**Comment by devonakerr** [comment]
Hm, do you mind throwing a "-d" before the script-runner? I'm wondering if this isn't caused by an environment variable of some kind. I tried to reproduce with a vanilla Ubuntu VM with Python 2.7.12 and didn't get dropped into interactive mode.

**Comment by rw-access** [comment]
Also, it looks like it's running on Ubuntu, but all of the RTAs require Windows. Is it working on your Windows computer?

**Comment by WangKaiWenCalvin** [comment]
> Also, it looks like it's running on Ubuntu, but all of the RTAs require Windows. Is it working on your Windows computer?

I'm sorry, I did not realize I need Windows in order to run all of the RTAs.  I just installed the tool on my Windows computer and it works. Thanks for the help.

> Hm, do you mind throwing a "-d" before the script-runner? I'm wondering if this isn't caused by an environment variable of some kind. I tried to reproduce with a vanilla Ubuntu VM with Python 2.7.12 and didn't get dropped into interactive mode.

Unfortunately, it did not produce anything new when I ran the command with "-d".  @rw-access mentioned that I needed to use Windows in order to run all the RTAs. Thanks for the help.
